// Fill in  your WiFi networks SSID and password
#define SECRET_SSID "YJ"
#define SECRET_PASS "aaaassss"

// Fill in the hostname of your AWS IoT broker
#define SECRET_BROKER "a26rhvhsnyf6yu-ats.iot.ap-northeast-2.amazonaws.com"

// Fill in the boards public certificate
const char SECRET_CERTIFICATE[] = R"(
-----BEGIN CERTIFICATE-----
MIICiDCCAXCgAwIBAgIUHkbvtiptxZXFzKoXw1UjH9xxB20wDQYJKoZIhvcNAQEL
BQAwTTFLMEkGA1UECwxCQW1hem9uIFdlYiBTZXJ2aWNlcyBPPUFtYXpvbi5jb20g
SW5jLiBMPVNlYXR0bGUgU1Q9V2FzaGluZ3RvbiBDPVVTMB4XDTIwMTIxMTA5NTA0
OFoXDTQ5MTIzMTIzNTk1OVowGDEWMBQGA1UEAxMNTXlNS1JXaUZpMTAxMDBZMBMG
ByqGSM49AgEGCCqGSM49AwEHA0IABA8SNvUMaj4JNNeNsNkRc4nwA8TBNEyDfkjN
0ByZAZWMqjUarJIYncxnSFYicwzAvPB848mlIjB+AxZkXc4Q9wmjYDBeMB8GA1Ud
IwQYMBaAFA0T+pWT7yxwnWVinxEZLJiJ08faMB0GA1UdDgQWBBTYsOnz0KBumq5Q
u8FDCb4nZQPo/zAMBgNVHRMBAf8EAjAAMA4GA1UdDwEB/wQEAwIHgDANBgkqhkiG
9w0BAQsFAAOCAQEAMBkH+GGwHkKydGsFSDvjO26dMTifLVJYPREoyYjlw98lvpN4
XnSXjO6RR7uOAEZCf2yNm9bJPdoTGzzlOV44/9NEs6i5VGekoeq4s9z8zCBtvcem
2gHTfdpZJmMvvYMTB7inrb58x6YXuvrK7FZmXP8/F2C2/OyIDYmIOIcjIQf1Y6+U
/MgfDYuRazvW9IBD0CHJa4KKHs/1e1To+iuQDea/7Ec0/hI8SrIgz3j8ScnRbZij
c1XOoVNRTJde0RzH3tHkpWLw/lkRImPpt4C2NaNOzzB5NtubEe5emSLdB4TiMCCs
EWghlJ18rdzt9MKg06/QaCzMzLcr9owHaGYRgA==
-----END CERTIFICATE-----


)";
